/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Model.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.633, -0.416, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Cube001__0.geometry} material={nodes.Cube001__0.material} position={[-0.134, 0.67, -0.515]} rotation={[0, 0, -1.557]} />
          </group>
          <group position={[1.633, -0.525, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Cube002_white_0.geometry} material={nodes.Cube002_white_0.material} position={[-0.044, 0.074, 0.24]} />
          </group>
          <group position={[0.24, -1.092, -0.295]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <mesh geometry={nodes.Cube003_black_0.geometry} material={nodes.Cube003_black_0.material} position={[-0.228, -0.179, -0.017]} />
            <mesh geometry={nodes.Cube003_white_0.geometry} material={nodes.Cube003_white_0.material} position={[-0.083, -0.052, -0.024]} />
          </group>
          <group position={[2.273, -1.056, 1.029]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cube012_Rgb_lighting_0.geometry} material={nodes.Cube012_Rgb_lighting_0.material} position={[-0.201, 0, -0.043]} />
            <mesh geometry={nodes.Cube012_white_0.geometry} material={nodes.Cube012_white_0.material} position={[-0.1, -0.003, -0.035]} />
          </group>
          <group position={[1.139, -0.739, -0.327]} rotation={[Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Cube016_black_cloth_0.geometry} material={nodes.Cube016_black_cloth_0.material} position={[0, 0, -0.001]} />
          </group>
          <group position={[1.371, -0.738, -0.284]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cube017_Material003_0.geometry} material={nodes.Cube017_Material003_0.material} position={[0, 0.068, 0.026]} />
            <mesh geometry={nodes.Cube017_Rgb_lighting_0.geometry} material={nodes.Cube017_Rgb_lighting_0.material} position={[0, 0.064, 0.029]} />
          </group>
          <group position={[1.137, -0.811, -0.721]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cube022__0.geometry} material={nodes.Cube022__0.material} position={[0, -0.009, 0.132]} />
          </group>
          <group position={[1.054, -0.708, -0.305]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cube105_Material004_0.geometry} material={nodes.Cube105_Material004_0.material} position={[-0.054, -0.005, 0.018]} />
            <mesh geometry={nodes.Cube105_Material005_0.geometry} material={nodes.Cube105_Material005_0.material} position={[-0.069, 0.016, -0.008]} />
            <mesh geometry={nodes.Cube105_Rgb_lighting_0.geometry} material={nodes.Cube105_Rgb_lighting_0.material} position={[-0.052, -0.005, 0.01]} />
          </group>
          <group position={[0.139, -0.833, -0.701]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cylinder__0.geometry} material={nodes.Cylinder__0.material} position={[0, 0.001, -0.021]} />
          </group>
          <group position={[0.602, -0.739, -0.284]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <group position={[-0.014, -0.029, 0.095]} rotation={[0.798, -0.409, -0.078]}>
              <mesh geometry={nodes.Cylinder002_leaves_0.geometry} material={nodes.Cylinder002_leaves_0.material} position={[0.003, 0.024, -0.025]} />
            </group>
            <mesh geometry={nodes.Cylinder001__0.geometry} material={nodes.Cylinder001__0.material} position={[0, -0.007, 0.072]} />
          </group>
          <group position={[2.633, 0.193, 0.305]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
            <mesh geometry={nodes.HoneyComb_Rgb_lighting_0.geometry} material={nodes.HoneyComb_Rgb_lighting_0.material} position={[-0.341, 1.13, -1.774]} rotation={[1.563, 0.004, 0.035]} scale={1.214} />
          </group>
          <group position={[0.108, -0.878, -0.687]} rotation={[0, 0.239, 0]}>
            <mesh geometry={nodes.Plane_leaves_0.geometry} material={nodes.Plane_leaves_0.material} position={[0.03, 0.118, -0.008]} />
          </group>
          <group position={[1.065, -0.81, 0.075]} rotation={[0, 0, -Math.PI]}>
            <group position={[-0.051, 0.309, 0.002]} rotation={[0, -0.516, 0]}>
              <group position={[0.143, 0.202, 0.188]} rotation={[-Math.PI, 1.121, -Math.PI]}>
                <mesh geometry={nodes.Circle002_black_0001.geometry} material={nodes.Circle002_black_0001.material} position={[-0.272, -1.541, -0.563]} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Cube034.geometry} material={nodes.Cube034.material} position={[2.604, 2.764, 0.248]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.532, 1, 1]} />
      <mesh geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[1.154, 1.676, -0.718]} rotation={[1.558, 0.013, -3.11]} />
    </group>
  )
}

useGLTF.preload('/Model.gltf')
