/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Rooms.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rooms.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[6.739, -0.126, 5.324]} rotation={[-3.065, 1.398, 3.047]}>
        <group position={[5.101, 1.125, -6.685]} rotation={[0, -0.22, 0]}>
          <mesh geometry={nodes.Cube_72003.geometry} material={nodes.Cube_72003.material} position={[-1.576, 0.472, -0.005]} rotation={[-2.416, 0.148, -1.574]} />
        </group>
      </group>
      <group position={[2.633, 2.291, 0.305]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.HoneyComb_Rgb_lighting_0.geometry} material={nodes.HoneyComb_Rgb_lighting_0.material} position={[-0.341, 1.184, -1.774]} rotation={[1.569, 0.003, 0.038]} />
      </group>
      <group position={[0.616, 1.454, -0.313]} rotation={[-2.369, 0.409, 3.064]}>
        <mesh geometry={nodes.Cylinder002_leaves_0.geometry} material={nodes.Cylinder002_leaves_0.material} position={[0.029, -0.104, 0.012]} />
      </group>
      <group position={[0.139, 1.265, -0.701]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder__0.geometry} material={nodes.Cylinder__0.material} position={[0, 0.045, -0.085]} />
      </group>
      <group position={[1.054, 1.39, -0.305]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube105_Material004_0.geometry} material={nodes.Cube105_Material004_0.material} position={[-0.053, 0.088, -0.06]} />
      </group>
      <group position={[1.137, 1.287, -0.721]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube022__0.geometry} material={nodes.Cube022__0.material} position={[0, -0.033, 0.067]} />
      </group>
      <group position={[1.371, 1.36, -0.284]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube017_Material003_0.geometry} material={nodes.Cube017_Material003_0.material} position={[0, 0.187, -0.039]} />
      </group>
      <group position={[1.139, 1.359, -0.327]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Cube016_black_cloth_0.geometry} material={nodes.Cube016_black_cloth_0.material} position={[0, 0.119, 0.064]} />
      </group>
      <group position={[2.273, 1.042, 1.029]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube012_Rgb_lighting_0.geometry} material={nodes.Cube012_Rgb_lighting_0.material} position={[-0.201, 0, -0.089]} />
        <mesh geometry={nodes.Cube012_white_0.geometry} material={nodes.Cube012_white_0.material} position={[-0.09, -0.003, -0.09]} />
      </group>
      <group position={[0.24, 1.005, -0.293]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.Cube003_white_0.geometry} material={nodes.Cube003_white_0.material} position={[-0.083, 0.067, 0.035]} />
      </group>
      <group position={[1.633, 1.573, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Cube002_white_0.geometry} material={nodes.Cube002_white_0.material} position={[-0.044, 0.194, 0.304]} />
      </group>
      <group position={[1.633, 1.682, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Cube001__0.geometry} material={nodes.Cube001__0.material} position={[-0.134, 0.696, -0.515]} rotation={[0, 0, -1.557]} />
      </group>
      <mesh geometry={nodes.object_0.geometry} material={nodes.object_0.material} position={[0.477, -1.657, -0.615]} rotation={[3.14, 0.206, -3.141]} />
      <mesh geometry={nodes.monitor2_back.geometry} material={nodes.monitor2_back.material} position={[2.29, 2.902, 1.116]} rotation={[-Math.PI, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} position={[-0.098, 0.098, 0.831]} />
      <mesh geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} position={[2.616, 2.862, 0.248]} rotation={[-Math.PI, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} position={[2.13, 2.72, -0.857]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Cube041.geometry} material={nodes.Cube041.material} position={[2.82, 2.39, -0.72]} rotation={[-0.056, 0.018, -1.876]} />
      <mesh geometry={nodes.Monitor_back.geometry} material={nodes.Monitor_back.material} position={[1.154, 1.709, -0.695]} rotation={[1.558, 0.013, -3.11]} />
      <mesh geometry={nodes.Cube_60001.geometry} material={nodes.Cube_60001.material} position={[-0.574, 0.894, 2.949]} rotation={[-Math.PI / 2, 0, -1.575]} />
      <mesh geometry={nodes.Cube046.geometry} material={nodes.Cube046.material} position={[-2.097, 0.393, 2.006]} />
      <mesh geometry={nodes.Monitor.geometry} material={nodes.Monitor.material} position={[1.154, 1.709, -0.695]} rotation={[1.558, 0.013, -3.11]} />
      <mesh geometry={nodes.monitor2.geometry} material={nodes.monitor2.material} position={[2.29, 2.902, 1.116]} rotation={[-Math.PI, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[1.632, 2.164, -0.523]} rotation={[1.571, 0, 0]} scale={0.096} />
      <mesh geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[2.567, 2.39, -0.72]} rotation={[-0.056, 0.018, -1.876]} />
      <mesh geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} position={[2.616, 2.39, -0.72]} rotation={[-0.056, 0.018, -1.876]} />
      <mesh geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[2.722, 2.377, -0.72]} rotation={[-0.058, 0.011, -1.919]} />
      <mesh geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} position={[2.672, 2.377, -0.72]} rotation={[-0.058, 0.011, -1.919]} />
      <mesh geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[2.771, 2.39, -0.72]} rotation={[-0.056, 0.018, -1.876]} />
      <mesh geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[2.865, 2.39, -0.72]} rotation={[-0.056, 0.018, -1.876]} />
    </group>
  )
}

useGLTF.preload('/Rooms.glb')
