/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Roomx-test.glb -T 
Files: Roomx-test.glb [1.78MB] > /home/fahad/Desktop/portfolio/portfolio/public/models/Roomx-test-transformed.glb [73.82KB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roomx-test-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.object_0.geometry} material={nodes.object_0.material} position={[0.7, 1.362, 0.711]} rotation={[3.14, 0.206, -3.141]} />
      <instancedMesh args={[nodes.Cube010.geometry, nodes.Cube010.material, 7]} instanceMatrix={nodes.Cube010.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/Roomx-test-transformed.glb')
