/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Roomx.glb --transform --simplify 
Files: Roomx.glb [1.77MB] > /home/fahad/Desktop/portfolio/portfolio/public/models/Roomx-transformed.glb [16.98KB] (99%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roomx-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.object_0.geometry} material={nodes.object_0.material} position={[0.477, -1.657, -0.615]} rotation={[3.14, 0.206, -3.141]} />
      <instancedMesh args={[nodes.Cube010.geometry, nodes.Cube010.material, 7]} instanceMatrix={nodes.Cube010.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/Roomx-transformed.glb')
