/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 untitled.glb 
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/untitled.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sofa_Pink"
          position={[2.536, 1.972, 2.02]}
          rotation={[-0.012, -0.008, 0.011]}
        >
          <group name="sofa" rotation={[0, 1.571, 0]} />
        </group>
        <group
          name="Plane003"
          position={[1.065, 1.288, 0.075]}
          rotation={[0, 0, -Math.PI]}
        >
          <group
            name="Plane001"
            position={[0, -0.227, 0.166]}
            rotation={[Math.PI / 2, 0, Math.PI]}
          >
            <group name="Plane001_white_cloth_0" />
            <group
              name="Plane004"
              position={[0, -0.015, -0.154]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
            >
              <group name="Plane004__0" />
            </group>
          </group>
          <group name="Plane002" position={[0, 0.057, -0.032]}>
            <group name="Plane002_white_cloth_0" />
          </group>
          <group name="Plane003_white_0" />
          <group
            name="Plane005"
            position={[-0.051, 0.309, 0.002]}
            rotation={[0, -0.516, 0]}
          />
        </group>
        <group
          name="Plane"
          position={[0.108, 1.22, -0.687]}
          rotation={[0, 0.239, 0]}
        />
        <group name="Object_2002" position={[-0.806, 2.098, 0]}>
          <group name="RootNode002">
            <group
              name="Cube026"
              position={[0.449, -1.137, 0.849]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
            />
          </group>
        </group>
        <group name="Object_2001" position={[-0.577, 2.098, 0]}>
          <group name="RootNode001">
            <group
              name="Cube015"
              position={[0.449, -1.137, 0.849]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <group
              name="Cube018"
              position={[0.449, -1.137, 0.849]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
            />
          </group>
        </group>
        <group name="Object_2" position={[0, 2.098, 0]} />
        <group
          name="Node_0001"
          position={[6.739, -0.126, 5.324]}
          rotation={[-3.065, 1.398, 3.047]}
        >
          <group name="Scene_1001">
            <group
              name="Sofa_Pink002"
              position={[5.101, 1.125, -6.685]}
              rotation={[0, -0.22, 0]}
            >
              <mesh
                name="Cube_72003"
                geometry={nodes.Cube_72003.geometry}
                material={nodes.Cube_72003.material}
                position={[-1.576, 0.472, -0.005]}
                rotation={[-2.416, 0.148, -1.574]}
              />
            </group>
          </group>
        </group>
        <group name="Node_0" position={[-4.396, -0.735, 8.56]}>
          <group name="Scene_1">
            <group
              name="Sofa_Pink001"
              position={[5.101, 1.125, -6.685]}
              rotation={[0, -0.22, 0]}
            />
          </group>
        </group>
        <group
          name="model_0"
          position={[2.469, 2.021, -0.242]}
          rotation={[-Math.PI / 2, -0.008, Math.PI / 2]}
        />
        <group
          name="HoneyComb"
          position={[2.633, 2.291, 0.305]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        >
          <mesh
            name="HoneyComb_Rgb_lighting_0"
            geometry={nodes.HoneyComb_Rgb_lighting_0.geometry}
            material={nodes.HoneyComb_Rgb_lighting_0.material}
            position={[-0.341, 1.184, -1.774]}
            rotation={[1.569, 0.003, 0.038]}
          />
        </group>
        <group
          name="Cylinder004"
          position={[0.634, 1.444, -0.287]}
          rotation={[-1.304, 0.777, 1.442]}
        />
        <group
          name="Cylinder002"
          position={[0.616, 1.454, -0.313]}
          rotation={[-2.369, 0.409, 3.064]}
        >
          <mesh
            name="Cylinder002_leaves_0"
            geometry={nodes.Cylinder002_leaves_0.geometry}
            material={nodes.Cylinder002_leaves_0.material}
            position={[0.029, -0.104, 0.012]}
          />
        </group>
        <group
          name="Cylinder"
          position={[0.139, 1.265, -0.701]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Cylinder__0"
            geometry={nodes.Cylinder__0.geometry}
            material={nodes.Cylinder__0.material}
            position={[0, 0.045, -0.085]}
          />
        </group>
        <group
          name="Cube105"
          position={[1.054, 1.39, -0.305]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Cube105_Material004_0"
            geometry={nodes.Cube105_Material004_0.geometry}
            material={nodes.Cube105_Material004_0.material}
            position={[-0.053, 0.088, -0.06]}
          />
        </group>
        <group
          name="Cube034"
          position={[3.139, 3.012, 1.36]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <group
          name="Cube032"
          position={[1.948, 1.287, -0.538]}
          rotation={[-Math.PI / 2, 0, -0.471]}
        />
        <group
          name="Cube031"
          position={[1.808, 1.573, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube030"
          position={[2.576, 2.352, 2.158]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <group
          name="Cube029"
          position={[2.459, 2.239, -0.585]}
          rotation={[-Math.PI / 2, 0, -0.049]}
        />
        <group
          name="Cube028"
          position={[-0.011, 2.349, -0.815]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <group
          name="Cube027"
          position={[2.144, 2.349, -0.815]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <group
          name="Cube025"
          position={[2.355, 1.656, 0.226]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group name="Cube025_white_0" />
        </group>
        <group
          name="Cube024"
          position={[1.925, 1.656, -0.497]}
          rotation={[-Math.PI / 2, 0, -0.475]}
        />
        <group
          name="Cube023"
          position={[2.48, 1.287, 0.224]}
          rotation={[-Math.PI / 2, 0, -1.586]}
        />
        <group
          name="Cube022"
          position={[1.137, 1.287, -0.721]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Cube022__0"
            geometry={nodes.Cube022__0.geometry}
            material={nodes.Cube022__0.material}
            position={[0, -0.033, 0.067]}
          />
        </group>
        <group
          name="Cube021"
          position={[1.137, 1.656, -0.597]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group name="Cube021_purple_emit_0" />
        </group>
        <group
          name="Cube020"
          position={[2.077, 1.357, 0.495]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <group
          name="Cube019"
          position={[2.156, 1.361, 0.275]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <group
          name="Cube017"
          position={[1.371, 1.36, -0.284]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Cube017_Material003_0"
            geometry={nodes.Cube017_Material003_0.geometry}
            material={nodes.Cube017_Material003_0.material}
            position={[0, 0.187, -0.039]}
          />
        </group>
        <group
          name="Cube016"
          position={[1.139, 1.359, -0.327]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="Cube016_black_cloth_0"
            geometry={nodes.Cube016_black_cloth_0.geometry}
            material={nodes.Cube016_black_cloth_0.material}
            position={[0, 0.119, 0.064]}
          />
        </group>
        <group
          name="Cube014"
          position={[1.808, 1.573, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube013"
          position={[1.633, 1.36, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube012"
          position={[2.273, 1.042, 1.029]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Cube012_Rgb_lighting_0"
            geometry={nodes.Cube012_Rgb_lighting_0.geometry}
            material={nodes.Cube012_Rgb_lighting_0.material}
            position={[-0.201, 0, -0.089]}
          />
          <mesh
            name="Cube012_white_0"
            geometry={nodes.Cube012_white_0.geometry}
            material={nodes.Cube012_white_0.material}
            position={[-0.09, -0.003, -0.09]}
          />
        </group>
        <group
          name="Cube011"
          position={[0.144, 0.753, 1.153]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          name="Cube010"
          position={[1.808, 1.573, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <group name="Cube010__0" position={[0.006, 0, 0]} />
        </group>
        <group
          name="Cube009"
          position={[0.449, 0.961, 0.849]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube008"
          position={[0.449, 0.961, 0.849]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube007"
          position={[0.449, 0.961, 0.849]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube006"
          position={[0.449, 0.961, 0.849]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube005"
          position={[0.449, 0.961, 0.849]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube004"
          position={[0.449, 0.961, 0.849]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <group
          name="Cube003"
          position={[0.24, 1.005, -0.293]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        >
          <mesh
            name="Cube003_white_0"
            geometry={nodes.Cube003_white_0.geometry}
            material={nodes.Cube003_white_0.material}
            position={[-0.083, 0.067, 0.035]}
          />
        </group>
        <group
          name="Cube002"
          position={[1.633, 1.573, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="Cube002_white_0"
            geometry={nodes.Cube002_white_0.geometry}
            material={nodes.Cube002_white_0.material}
            position={[-0.044, 0.194, 0.304]}
          />
        </group>
        <group
          name="Cube001"
          position={[1.633, 1.682, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="Cube001__0"
            geometry={nodes.Cube001__0.geometry}
            material={nodes.Cube001__0.material}
            position={[-0.134, 0.696, -0.515]}
            rotation={[0, 0, -1.557]}
          />
        </group>
        <group
          name="Cube"
          position={[1.808, 1.573, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <PerspectiveCamera
          name="Camera001"
          makeDefault={false}
          far={100.3}
          near={0.1}
          fov={19.475}
          position={[1.409, 1.348, 1.447]}
          rotation={[0.013, 0.07, 0.034]}
        />
        <mesh
          name="Text001"
          geometry={nodes.Text001.geometry}
          material={nodes.Text001.material}
          position={[1.632, 2.164, -0.523]}
          rotation={[1.571, 0, 0]}
          scale={0.096}
        />
        <mesh
          name="object_0"
          geometry={nodes.object_0.geometry}
          material={nodes.object_0.material}
          position={[0.477, -1.657, -0.615]}
          rotation={[3.14, 0.206, -3.141]}
        />
        <mesh
          name="Monitor_back"
          geometry={nodes.Monitor_back.geometry}
          material={nodes.Monitor_back.material}
          position={[1.154, 1.709, -0.695]}
          rotation={[1.558, 0.013, -3.11]}
        />
        <mesh
          name="monitor2_back"
          geometry={nodes.monitor2_back.geometry}
          material={nodes.monitor2_back.material}
          position={[2.29, 2.902, 1.116]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          name="monitor2"
          geometry={nodes.monitor2.geometry}
          material={nodes.monitor2.material}
          position={[2.29, 2.902, 1.116]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          name="Monitor"
          geometry={nodes.Monitor.geometry}
          material={nodes.Monitor.material}
          position={[1.154, 1.709, -0.695]}
          rotation={[1.558, 0.013, -3.11]}
        />
        <mesh
          name="Cube046"
          geometry={nodes.Cube046.geometry}
          material={nodes.Cube046.material}
          position={[-2.097, 0.393, 2.006]}
        />
        <mesh
          name="Cube044"
          geometry={nodes.Cube044.geometry}
          material={nodes.Cube044.material}
          position={[-0.098, 0.098, 0.831]}
        />
        <mesh
          name="Cube043"
          geometry={nodes.Cube043.geometry}
          material={nodes.Cube043.material}
          position={[2.616, 2.862, 0.248]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          name="Cube042"
          geometry={nodes.Cube042.geometry}
          material={nodes.Cube042.material}
          position={[2.13, 2.72, -0.857]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          name="Cube041"
          geometry={nodes.Cube041.geometry}
          material={nodes.Cube041.material}
          position={[2.82, 2.39, -0.72]}
          rotation={[-0.056, 0.018, -1.876]}
        />
        <mesh
          name="Cube040"
          geometry={nodes.Cube040.geometry}
          material={nodes.Cube040.material}
          position={[2.672, 2.377, -0.72]}
          rotation={[-0.058, 0.011, -1.919]}
        />
        <mesh
          name="Cube038"
          geometry={nodes.Cube038.geometry}
          material={nodes.Cube038.material}
          position={[2.771, 2.39, -0.72]}
          rotation={[-0.056, 0.018, -1.876]}
        />
        <mesh
          name="Cube037"
          geometry={nodes.Cube037.geometry}
          material={nodes.Cube037.material}
          position={[2.616, 2.39, -0.72]}
          rotation={[-0.056, 0.018, -1.876]}
        />
        <mesh
          name="Cube036"
          geometry={nodes.Cube036.geometry}
          material={nodes.Cube036.material}
          position={[2.567, 2.39, -0.72]}
          rotation={[-0.056, 0.018, -1.876]}
        />
        <mesh
          name="Cube035"
          geometry={nodes.Cube035.geometry}
          material={nodes.Cube035.material}
          position={[2.865, 2.39, -0.72]}
          rotation={[-0.056, 0.018, -1.876]}
        />
        <mesh
          name="Cube033"
          geometry={nodes.Cube033.geometry}
          material={nodes.Cube033.material}
          position={[2.722, 2.377, -0.72]}
          rotation={[-0.058, 0.011, -1.919]}
        />
        <mesh
          name="Cube_60001"
          geometry={nodes.Cube_60001.geometry}
          material={nodes.Cube_60001.material}
          position={[-0.574, 0.894, 2.949]}
          rotation={[-Math.PI / 2, 0, -1.575]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/untitled.glb");
