/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/bbhome.glb");
  const texture = useTexture("/textures/baked.jpg");
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBToLinear;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  textureMaterial.metalness = -1

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });

  return (
    <group {...props} dispose={null}>
      <group position={[-0.461, -1.283, -0.515]} scale={0.561}>
        <mesh geometry={nodes.Room.geometry} 
        // material={nodes.Room.material}
        material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.object_0.geometry}
          // material={nodes.object_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cylinder002_leaves_0.geometry}
          // material={nodes.Cylinder002_leaves_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube045.geometry}
          // material={nodes.Cube045.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube043.geometry}
          // material={nodes.Cube043.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube042.geometry}
          // material={nodes.Cube042.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube041.geometry}
          // material={nodes.Cube041.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube040.geometry}
          // material={nodes.Cube040.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube039.geometry}
          // material={nodes.Cube039.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube038.geometry}
          // material={nodes.Cube038.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube037.geometry}
          // material={nodes.Cube037.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube036.geometry}
          // material={nodes.Cube036.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube035.geometry}
          // material={nodes.Cube035.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube033.geometry}
          // material={nodes.Cube033.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_72003.geometry}
          // material={nodes.Cube_72003.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_72002.geometry}
          // material={nodes.Cube_72002.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_63002.geometry}
          // material={nodes.Cube_63002.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_63001.geometry}
          // material={nodes.Cube_63001.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_63.geometry}
          // material={nodes.Cube_63.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_60001.geometry}
          // material={nodes.Cube_60001.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_59001.geometry}
          // material={nodes.Cube_59001.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_58001.geometry}
          // material={nodes.Cube_58001.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube_57.geometry}
          // material={nodes.Cube_57.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube044.geometry}
          // material={nodes.Cube044.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube001__0.geometry}
          // material={nodes.Cube001__0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube002_white_0.geometry}
          // material={nodes.Cube002_white_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube003_white_0.geometry}
          // material={nodes.Cube003_white_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube012_Rgb_lighting_0.geometry}
          // material={nodes.Cube012_Rgb_lighting_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube012_white_0.geometry}
          // material={nodes.Cube012_white_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube016_black_cloth_0.geometry}
          // material={nodes.Cube016_black_cloth_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube017_Material003_0.geometry}
          // material={nodes.Cube017_Material003_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube017_Rgb_lighting_0.geometry}
          // material={nodes.Cube017_Rgb_lighting_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube022__0.geometry}
          // material={nodes.Cube022__0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube105_Material004_0.geometry}
          // material={nodes.Cube105_Material004_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube105_Material005_0.geometry}
          // material={nodes.Cube105_Material005_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube105_Rgb_lighting_0.geometry}
          // material={nodes.Cube105_Rgb_lighting_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cylinder__0.geometry}
          // material={nodes.Cylinder__0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.HoneyComb_Rgb_lighting_0.geometry}
          // material={nodes.HoneyComb_Rgb_lighting_0.material}
          material={textureMaterial}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/scene.glb");
