/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 monkey.glb 
*/

import { useGLTF, useTexture } from "@react-three/drei";
import React from "react";

import * as THREE from "three";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/monkey.glb");
  const texture = useTexture("/textures/baked-monkey.png");
  texture.flipY = false;
  texture.colorSpace = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Suzanne.geometry}
        // material={nodes.Suzanne.material}
        material={textureMaterial}
        position={[0.119, 1.103, -0.247]}
      >
        <meshBasicMaterial map={texture}/>
        </mesh>
    </group>
  );
}

useGLTF.preload("/monkey.glb");
