/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 /home/fahad/Desktop/portfolio/portfolio/public/models/roomx.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/roomx.glb");
  try {
    const texture = useTexture("/textures/baked.jpg");
    texture.flipY = false;
    texture.colorSpace = THREE.sRGBEncoding;
    
  } catch (error) {
    console.log(error);
  }
  // const textureMaterial = new THREE.MeshStandardMaterial({
  //   map: texture,
  // });

  // const textureGlassMaterial = new THREE.MeshStandardMaterial({
  //   map: texture,
  //   transparent: true,
  //   opacity: 0.42,
  // });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Rectangle_2.geometry}
        material={nodes.Rectangle_2.material}
        position={[-6.773, 14.682, -3.429]}
        rotation={[-1.563, 0.018, 1.571]}
        scale={0.206}
      />
      <mesh
        geometry={nodes.Rectangle_2002.geometry}
        material={nodes.Rectangle_2002.material}
        position={[-6.773, 14.682, -3.429]}
        rotation={[-1.563, 0.018, 1.571]}
        scale={0.206}
      />
      <mesh
        geometry={nodes.Rectangle_2003.geometry}
        material={nodes.Rectangle_2003.material}
        position={[-6.773, 14.682, -3.429]}
        rotation={[-1.563, 0.018, 1.571]}
        scale={0.206}
      />
      <mesh
        geometry={nodes.Rectangle_2004.geometry}
        material={nodes.Rectangle_2004.material}
        position={[-6.773, 14.682, -3.429]}
        rotation={[-1.563, 0.018, 1.571]}
        scale={0.206}
      />
      <mesh
        geometry={nodes.Rectangle_2007.geometry}
        material={nodes.Rectangle_2007.material}
        position={[-6.773, 14.682, -3.429]}
        rotation={[-1.563, 0.018, 1.571]}
        scale={0.206}
      />
    </group>
  );
}

useGLTF.preload("/models/roomx.glb");
