/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.glb 
*/

import React, { useMemo, useRef } from "react";
import {
  Float,
  Html,
  PerspectiveCamera,
  useGLTF,
  useTexture,
} from "@react-three/drei";
import * as THREE from "three";
import Home from "./Home";
import { useControls } from "leva";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/Modelings.glb");
  const texture = useTexture("/textures/trych.jpg ");
  texture.flipY = false;
  texture.colorSpace = THREE.sRGBEncoding;

  const textureMaterial = useRef(
    new THREE.MeshStandardMaterial({ map: texture })
  );

  textureMaterial.metalness = 1;

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });

  const options = useMemo(() => {
    return {
      x: { value: 0, min: -10, max: 50, step: 0.01 },
      y: { value: 0, min: -10, max: 50, step: 0.01 },
      z: { value: 0, min: -10, max: 50, step: 0.01 },
      visible: true,
      color: { value: "lime" },
    };
  }, []);

  const pA = useControls("Position", options);
  const rA = useControls("Rotate", options);

  return (
    <group
      {...props}
      dispose={null}
      position={[pA.x, pA.y, pA.z]}
      // rotation={[rA.x, rA.y, rA.z]}
      // position={[4.80, 3.50, 4.95]}
      rotation={[0, -4.93, 0]}
    >
      <group
        position={[6.739, -0.126, 5.324]}
        rotation={[-3.065, 1.398, 3.047]}
      >
        <group position={[5.101, 1.125, -6.685]} rotation={[0, -0.22, 0]}>
          <mesh
            geometry={nodes.Cube_72003.geometry}
            // material={nodes.Cube_72003.material}
            material={textureMaterial}
            position={[-1.576, 0.472, -0.005]}
            rotation={[-2.416, 0.148, -1.574]}
          >
            <meshBasicMaterial map={texture} />
          </mesh>
        </group>
      </group>
      <group
        position={[2.633, 2.291, 0.305]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
      >
        <mesh
          geometry={nodes.HoneyComb_Rgb_lighting_0.geometry}
          // material={nodes.HoneyComb_Rgb_lighting_0.material}
          material={textureMaterial}
          position={[-0.341, 1.184, -1.774]}
          rotation={[1.569, 0.003, 0.038]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group
        position={[0.616, 1.454, -0.313]}
        rotation={[-2.369, 0.409, 3.064]}
      >
        <mesh
          geometry={nodes.Cylinder002_leaves_0.geometry}
          // material={nodes.Cylinder002_leaves_0.material}
          material={textureMaterial}
          position={[0.029, -0.104, 0.012]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group position={[0.139, 1.265, -0.701]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cylinder__0.geometry}
          // material={nodes.Cylinder__0.material}
          material={textureMaterial}
          position={[0, 0.045, -0.085]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group position={[1.054, 1.39, -0.305]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube105_Material004_0.geometry}
          // material={nodes.Cube105_Material004_0.material}
          material={textureMaterial}
          position={[-0.053, 0.088, -0.06]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group position={[1.137, 1.287, -0.721]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube022__0.geometry}
          // material={nodes.Cube022__0.material}
          material={textureMaterial}
          position={[0, -0.033, 0.067]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group position={[1.371, 1.36, -0.284]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube017_Material003_0.geometry}
          // material={nodes.Cube017_Material003_0.material}
          material={textureMaterial}
          position={[0, 0.187, -0.039]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group
        position={[1.139, 1.359, -0.327]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cube016_black_cloth_0.geometry}
          // material={nodes.Cube016_black_cloth_0.material}
          material={textureMaterial}
          position={[0, 0.119, 0.064]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group position={[2.273, 1.042, 1.029]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube012_Rgb_lighting_0.geometry}
          // material={nodes.Cube012_Rgb_lighting_0.material}
          material={textureMaterial}
          position={[-0.201, 0, -0.089]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh
          geometry={nodes.Cube012_white_0.geometry}
          // material={nodes.Cube012_white_0.material}
          material={textureMaterial}
          position={[-0.09, -0.003, -0.09]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group
        position={[0.24, 1.005, -0.293]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <mesh
          geometry={nodes.Cube003_white_0.geometry}
          // material={nodes.Cube003_white_0.material}
          material={textureMaterial}
          position={[-0.083, 0.067, 0.037]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group position={[1.633, 1.573, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Cube002_white_0.geometry}
          // material={nodes.Cube002_white_0.material}
          material={textureMaterial}
          position={[-0.044, 0.194, 0.304]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <group position={[1.633, 1.682, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Cube001__0.geometry}
          // material={nodes.Cube001__0.material}
          material={textureMaterial}
          position={[-0.134, 0.696, -0.515]}
          rotation={[0, 0, -1.557]}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.object_0.geometry}
        // material={nodes.object_0.material}
        material={textureMaterial}
        position={[0.477, -1.657, -0.615]}
        rotation={[3.14, 0.206, -3.141]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.monitor2_back.geometry}
        // material={nodes.monitor2_back.material}
        material={textureMaterial}
        position={[2.29, 2.902, 1.116]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube044.geometry}
        // material={nodes.Cube044.material}
        material={textureMaterial}
        position={[-0.098, 0.098, 0.831]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube043.geometry}
        // material={nodes.Cube043.material}
        material={textureMaterial}
        position={[2.616, 2.862, 0.248]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube042.geometry}
        // material={nodes.Cube042.material}
        material={textureMaterial}
        position={[2.13, 2.72, -0.857]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube041.geometry}
        // material={nodes.Cube041.material}
        material={textureMaterial}
        position={[2.561, 2.39, -0.72]}
        rotation={[-0.056, 0.018, -1.876]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube035.geometry}
        // material={nodes.Cube035.material}
        material={textureMaterial}
        position={[2.561, 2.39, -0.718]}
        rotation={[-0.056, 0.018, -1.876]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Monitor_back.geometry}
        // material={nodes.Monitor_back.material}
        material={textureMaterial}
        position={[1.154, 1.709, -0.695]}
        rotation={[1.558, 0.013, -3.11]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube_60001.geometry}
        // material={nodes.Cube_60001.material}
        material={textureMaterial}
        position={[-0.574, 0.894, 2.949]}
        rotation={[-Math.PI / 2, 0, -1.575]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube046.geometry}
        // material={nodes.Cube046.material}
        material={textureMaterial}
        position={[-2.097, 0.393, 2.006]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Monitor.geometry}
        // material={nodes.Monitor.material}
        material={textureMaterial}
        position={[1.154, 1.709, -0.696]}
        rotation={[1.558, 0.013, -3.11]}
      >
        <Html
          className="w-[380px] h-[212px] p-3 bg-white"
          style={{ transform: "rotateY(180deg)" }}
          rotation-x={-Math.PI / 2}
          position={[0.0, -0.01, 0.0]}
          scale={0.1}
          transform
          fullscreen={true}
          occlude="blending"
          zIndexRange={99}
        >
          <div
            className="w-[370px] h-[216px]"
            onPointerDown={(e) => e.stopPropagation()}
          >
            <Home />
          </div>
        </Html>
      </mesh>
      <mesh
        geometry={nodes.Cube047.geometry}
        // material={nodes.Cube047.material}
        material={textureMaterial}
        position={[2.613, 2.39, -0.72]}
        rotation={[-0.056, 0.018, -1.876]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube039.geometry}
        // material={nodes.Cube039.material}
        material={textureMaterial}
        position={[2.819, 2.39, -0.725]}
        rotation={[-0.056, 0.019, -1.897]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube033.geometry}
        // material={nodes.Cube033.material}
        material={textureMaterial}
        position={[2.661, 2.39, -0.725]}
        rotation={[-0.056, 0.018, -1.876]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube038.geometry}
        // material={nodes.Cube038.material}
        material={textureMaterial}
        position={[2.718, 2.39, -0.725]}
        rotation={[-0.056, 0.019, -1.897]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Cube037.geometry}
        // material={nodes.Cube037.material}
        material={textureMaterial}
        position={[2.768, 2.39, -0.725]}
        rotation={[-0.056, 0.019, -1.897]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.monitor2.geometry}
        // material={nodes.monitor2.material}
        material={textureMaterial}
        position={[2.29, 2.902, 1.116]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
      >
        <Html
          className="w-[383px] h-[246px] p-3 bg-white rotate-360"
          style={{ transform: "rotateY(180deg)" }}
          rotation-x={-Math.PI / 2}
          rotation-z={-Math.PI / 2}
          rotation-y={Math.PI}
          position={[0.41, 0.14, -1.7]}
          scale={0.18}
          transform
          distanceFactor={10}
          prepend
          fullscreen={true}
          occlude="blending"
        >
          <div
            className="w-[370px] h-[216px]"
            onPointerDown={(e) => e.stopPropagation()}
          >
            <Home />
          </div>
        </Html>
      </mesh>
      <mesh
        geometry={nodes.Text001.geometry}
        // material={nodes.Text001.material}
        material={textureMaterial}
        position={[1.632, 2.164, -0.523]}
        rotation={[1.571, 0, 0]}
        scale={0.096}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Roomnew.gltf");
